### ISSUE TITLE
HostedForm is not showing up

### ISSUE THREAD

**Issue by dexterjohncaones** [brendanbond/react-acceptjs#5] opened 2023-03-29 07:39 UTC
I have observed that when the HostedForm is properly working, you should see the code existing inside the body of the page when you inspect its element. In our system, we are using react with material UI and placing the HostedForm inside the material Drawer, When I close the drawer and re-open it, the on-click function of the HostedForm form does not work anymore. It seems like the functionality that adds the `class="show"` to the element that makes the form appear is not working.

**Comment by brendanbond** [comment] 2023-03-30 17:21
I'm not sure I follow the issue, perhaps you can provide a minimal, reproducible example?

**Comment by dexterjohncaones** [comment] 2023-03-31 00:11
> I'm not sure I understand the specific issue enough to help, perhaps you can provide a minimal, reproducible example?
@brendanbond Here's the code sample. Thank you.
https://codesandbox.io/s/inspiring-thunder-ock17k?file=/src/App.js

**Comment by dexterjohncaones** [comment] 2023-04-04 03:43
@brendanbond Sometimes the library doesn't load properly. It comes with an error
![image](https://user-images.githubusercontent.com/21968120/229681754-9e556b3d-a505-4fa4-8e19-b4d70395fb5d.png)

**Comment by brendanbond** [comment] 2023-04-08 02:25
`<HostedForm />` is just a React wrapper for [this library](https://developer.authorize.net/api/reference/features/acceptjs.html#Integrating_the_Hosted_Payment_Information_Form). Both the error you describe and the behavior you're seeing, as you indicated, is something in the show/hide code in the [library itself](https://js.authorize.net/v3/AcceptUI.js) provided by Authorize.net. The solution might be to find the fix and host your forked version locally, but I won't have time to look more deeply as this library just aims to wrap it in idiomatic-ish React.

**Comment by brendanbond** [comment] 2023-04-08 02:26
Whoops, I pressed close accidentally! I'd like to leave this open in case you come to a solution in the library code, please post it if you do!

**Comment by pandas9** [comment] 2023-09-28 03:00
Had the same issue fixed by copying code from the git repository and creating a custom component

Due to the nature of react.js script sometimes won't load properly or it will load twice if any of that happens authorize net won't show the popup

**Comment by pandas9** [comment] 2023-09-28 03:01
Wrapper would be much better alternative to load the script same as stripe does it and then having to put payment button inside wrapper

**Comment by brendanbond** [comment] 2023-09-28 03:13
> Wrapper would be much better alternative to load the script same as stripe does it and then having to put payment button inside wrapper

Thanks, @pandas9 although I'm not sure I follow. The script is loaded via [this hook](https://github.com/brendanbond/react-acceptjs/blob/main/src/hooks/useScript.ts) - can you elaborate on how Stripe does something similar? FWIW, these components/hooks act as a fairly thin wrapper around the AcceptJS library, which is structured far differently from Stripe's (really excellent) React provider libraries. 

The truth is, I've moved on from the project that I wrote this for (although, to my knowledge, it still uses this library in production). I would welcome a PR if you have time to try and tackle the issue you're running into. Otherwise, I'll need some more context or concrete steps to reproduce any trouble you're having. Thanks!

**Comment by pstatxde** [comment] 2024-03-28 12:46
> Wrapper would be much better alternative to load the script same as stripe does it and then having to put payment button inside wrapper

We are hitting the same issue with HostedForm as @pandas9. In our 4 step checkout process in which the user can navigate forward and backward through the steps, the first time through clicking the "Pay" button displays the lightbox with credit card fields properly. Once we navigate away from that screen, then back to it, the button no longer opens the lightbox.

The issue occurs when the underlying component that HostedForm is on is loaded, then unloaded, then reloaded. For example, if HostedForm is on the "Payment" component, this code will cause the issue since it loads and unloads the Payment component depending on the checkout step the user is on: { step === 3 && <Payment /> }.

If I change the above code to simply hide the Payment component (as opposed to unloading it), the Pay button works correctly as the user navigates back and forth to the Payment component: <div className={step === 3 ? "d-block" : "d-none"}><Payment /></div>

**Comment by brendanbond** [comment] 2024-03-31 18:11
@pstatxde if I'm understanding correctly, the solution is to make sure that react doesn't unmount remount and remount the <HostedForm /> component - shouldn't that be taken care of at the component's consumer level, rather than in the component itself, or is there something that should be done to <HostedForm /> ?

**Comment by obsoke** [comment] 2024-04-03 19:43
I've been running into the same issue. The `<HostedForm />` modal pops up the first time you click the button but if you navigate to a new page & back, it no longer opens.

As an experiment, I commented out the `<HostedForm />` component from `react-acceptjs` and tried using `AcceptUI.js` + a `<button className="AcceptJS">` by itself (as documented by [authorize.net's docs](https://developer.authorize.net/api/reference/features/acceptjs.html)). I can confirm that this seems to be an issue not with `react-acceptjs` but the `AcceptUI.js` library. It looks like even though the `AcceptUI.js` remains in the `<head>`, if the component with `<HostedForm />` is unloaded/reloaded, the modal will not appear again.

My guess is that `AcceptUI.js` attaches an event listener to the button. Navigating away to another page within SPA means the button is unmounted from the DOM & re-visiting your component with `<HostedForm>` does not re-attach the event listener. My guess is probably accurate as the AcceptJS docs contain this warning:
> If you are building your page dynamically, be sure that your page loads the Accept JavaScript library after the button is defined. For the library to correctly interface with the button, the button must already exist in the DOM when the library is loaded.

The only solution I can think of would be a change to the `useScript` hook. Currently, there is a `cachedScripts` array that is used to prevent adding `AcceptUI.js` to the DOM multiple times. Instead, the solution might be to:

1. Check if the DOM already contains a `script[src=URL]` tag.
2. If it does, remove it.

The rest of the `useEffect()` hook in `useScript()` would proceed, adding `AcceptUI.js` to the DOM.

This is a bit hacky but without being able to modify `AcceptUI.js` directly, I'm not sure what other solutions there are. In a React SPA, it's expected that different components will unload / load into the DOM as the user navigates around the application. AcceptJS seems like an old library that was written for a pre-SPA world so special care might need to be taken to make it work properly with React.

If this solution is acceptable to @brendanbond, I'd be happy to open a merge request.

**Comment by brendanbond** [comment] 2024-04-04 04:24
@obsoke 
> Check if the DOM already contains a script[src=URL] tag. If it does, remove it.

Hmm, it seems like from your very good description of the problem, `<HostedForm />` (i.e. AcceptUI.js) is the only script that needs to be loaded after the button is instantiated in the DOM. Rather than modifying `useScript`, maybe that particular component could just load the script in a `useEffect` hook and then, on cleanup, remove it (we could even memoize the actual script content to avoid having to call to the network on mount and unmount). This way, the other two components are unaffected and `<HostedForm />` (which funnily enough is so distinct from the others that I considered making two separate libraries) can ensure that its AcceptUI script is loaded after the button. Your thoughts?

> If this solution is acceptable to @brendanbond, I'd be happy to open a merge request.

Feel free, that would be awesome!

**Comment by pstatxde** [comment] 2024-04-04 14:55
> @pstatxde if I'm understanding correctly, the solution is to make sure that react doesn't unmount remount and remount the component - shouldn't that be taken care of at the component's consumer level, rather than in the component itself, or is there something that should be done to ?

Sorry for the late reply. Your understanding is correct and my workaround was to ensure my component that HostedForm is on is hidden/unhidden rather than being unmounted/mounted in the DOM. That said, I think it's better if HostedForm works correctly when the underlying component is unmounted and remounted, since most apps likely work in that manner.

**Comment by pstatxde** [comment] 2024-04-04 14:58
> In a React SPA, it's expected that different components will unload / load into the DOM as the user navigates around the application. AcceptJS seems like an old library that was written for a pre-SPA world so special care might need to be taken to make it work properly with React.
Agreed.

> If this solution is acceptable to @brendanbond, I'd be happy to open a merge request.
This would be very helpful. Thank you as well.

**Comment by obsoke** [comment] 2024-04-04 18:24
> Rather than modifying `useScript`, maybe that particular component could just load the script in a `useEffect` hook and then, on cleanup, remove it (we could even memoize the actual script content to avoid having to call to the network on mount and unmount). This way, the other two components are unaffected and `<HostedForm />` (which funnily enough is so distinct from the others that I considered making two separate libraries) can ensure that its AcceptUI script is loaded after the button. Your thoughts?

By 'that particular component', do you mean `<HostedForm />`? Would this mean `<HostedForm />` would not use `useScript` after this change?

I do like the idea of memoizing the script content.

**Comment by brendanbond** [comment] 2024-04-04 18:25
> By 'that particular component', do you mean <HostedForm />? Would this mean <HostedForm /> would not use useScript after this change?

Yeah, it uses a separate script (AcceptUI.js) IIRC, so we can just ditch `useScript` for that one if that fits the bill for the fix.

**Comment by obsoke** [comment] 2024-04-04 18:32
Sounds like a plan! I'll spend some time on this today & tomorrow, expect a PR shortly!

**Closed** 2024-11-27 21:25 UTC

**Comment by joaogarin** [comment] 2026-03-30 14:01
@brendanbond 

Can we get this fix released in the npm package? It looks like this was never published? maybe something failed because it looked like the intention was to publish this fix 🤔 

<img width="221" height="391" alt="Image" src="https://github.com/user-attachments/assets/8257e5bd-842a-4b8a-883c-f694fcb7d086" />

**Comment by brendanbond** [comment] 2026-03-30 15:52
for sure, I'm not sure how it got missed, let me see if I can publish in the next few hours @joaogarin

**Comment by brendanbond** [comment] 2026-03-31 14:10
@joaogarin published as 0.5.1
